import { jsPDF } from 'jspdf';

/**
 * Generate a PDF from resume content
 * @param {Object} resumeData - Resume content and metadata
 * @returns {jsPDF} PDF document
 */
export function generatePDF(resumeData) {
  const doc = new jsPDF();
  const { content } = resumeData;

  // Set font
  doc.setFont('helvetica');

  // Title
  doc.setFontSize(20);
  doc.text('Resume', 105, 20, { align: 'center' });

  // Content
  doc.setFontSize(12);
  const lines = doc.splitTextToSize(content, 180);
  doc.text(lines, 15, 40);

  // Footer
  doc.setFontSize(10);
  doc.text(
    `Generated by Resume Build AI - ${new Date().toLocaleDateString()}`,
    105,
    280,
    { align: 'center' }
  );

  return doc;
}

/**
 * Download resume as PDF
 * @param {Object} resumeData - Resume content and metadata
 * @param {string} filename - Name of the PDF file
 */
export function downloadResumePDF(resumeData, filename = 'resume.pdf') {
  const doc = generatePDF(resumeData);
  doc.save(filename);
}

/**
 * Preview resume PDF in new tab
 * @param {Object} resumeData - Resume content and metadata
 */
export function previewResumePDF(resumeData) {
  const doc = generatePDF(resumeData);
  const pdfBlob = doc.output('blob');
  const url = URL.createObjectURL(pdfBlob);
  window.open(url, '_blank');
}
